travis:
  secure:
    BINSTAR_TOKEN: gLbI7Ao/8OlQMQm2Yn2UP7dsULLji0RJH90CbGdAxJe4uaVbPXc0W5EVtl8gLS3OUcrBoz03QPXXPXS6u0mjNdS4Wi0MV0yuWb9OboTeaoxdKGMfVGWgBquT1XSYcRyCHYhn2vAY2c1YAInk9fbUZA7IC1cFoLmNsbPmQ0FwreMUDoIyP+Cc+Jl31l2++wfdDAnj61EtsED6rx7eY7viiylgwt4RLP9Jvw24hCRE4ykswzLvvyeU5UFPgZ6eStKpBklVlMIzrE9iSVqZGYzfvwa5zjB+J7Chq8j0lwhLFlJdPWsecM4CdI0jEcTyNWaJjZ8rXxPAxlws+V8YB3gqBoPklGTVxuqTXdQBF12Pw33LuLTKhfSFK2rTQn5x/c+r5H9btf9BskcV3s9M4LPdJPWLxNVwm4yn+uKj1a5t76R0umt+Trt+3qjDDH4UR3Ai9zA+Mv8/hs2nMN1WF13rhqfGMSr5BjOjVeIQUKOdvkjcp8sjUDCyIwieaVsUxFlDxUULC0JDgklY7MCTI4OH4jyh7pRav/cDElA/Zi4miP7bDMG3OG7JbR+RfpScgMidCCsFZqtyS4CCNZWaiUuKvkstLCa4lxb7MDV6tbqmRFdant08Ck9y/4oJ0yxya6VIxoSAMJbjlwmYJ67guMyFDRvH0sQyebdmgjVNvAo2UaE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
